[project]
name = "opt-gemm-with-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fabric>=3.2.2",
    "gymnasium>=1.2.3",
    "ipywidgets>=8.1.8",
    "jinja2>=3.1.6",
    "jupyterlab>=4.5.1",
    "jupyterlab-language-pack-zh-cn>=4.4.post3",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "openpyxl>=3.1.5",
    "optuna>=4.6.0",
    "optuna-dashboard>=0.20.0",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.3.260113",
    "paramiko>=4.0.0",
    "plotly>=6.5.0",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy-stubs~=1.16.3",
    "seaborn>=0.13.2",
    "tensorboard>=2.20.0",
    "tianshou==2.0.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "xgboost>=3.1.2",
]


[tool.uv]
# 这里设置你的项目默认的 PyPI 源
index-url = "https://mirrors.ustc.edu.cn/pypi/simple"
python-install-mirror = "https://registry.npmmirror.com/-/binary/python-build-standalone/"

#[[tool.uv.index]]
#name = "pytorch-cu126"
#url = "https://download.pytorch.org/whl/cu126"
#explicit = true  # 建议开启，防止其他非 PyTorch 包误从该源下载

#[tool.uv.sources]
#torch = { index = "pytorch-cu126" }
#torchvision = { index = "pytorch-cu126" }
#torchaudio = { index = "pytorch-cu126" }
#
[tool.basedpyright]
typeCheckingMode = "strict"
ignore = ["**/__pycache__"]
