# External baseline discovery and published adapter targets.
# Third-party sources are not included; provide explicit install prefixes.

set(OPENBLAS_ROOT "" CACHE PATH "OpenBLAS 0.3.30 installation prefix")
set(ARMPL_ROOT "" CACHE PATH "Arm Performance Libraries 25.07 installation prefix")
set(EIGEN_ROOT "" CACHE PATH "Eigen 3.4.0 installation prefix")
set(BLIS_ROOT "" CACHE PATH "BLIS 2.0 installation prefix")
set(LIBXSMM_ROOT "" CACHE PATH "LIBXSMM feature_sw_pipeline_panels-1.17-3834 prefix")
set(BLASFEO_ROOT "" CACHE PATH "BLASFEO 0.1.4.2 installation prefix")
set(LIBSHALOM_ROOT "" CACHE PATH "LibShalom prefix (AnonymousYWL/TPDS)")
set(CAKE_ROOT "" CACHE PATH "CAKE prefix (vnatesh/CAKE_on_CPU)")

find_path(OPENBLAS_INCLUDE_DIR NAMES cblas.h HINTS "${OPENBLAS_ROOT}" ENV OPENBLAS_ROOT
    PATH_SUFFIXES include include/openblas NO_DEFAULT_PATH)
find_library(OPENBLAS_LIBRARY NAMES openblas HINTS "${OPENBLAS_ROOT}" ENV OPENBLAS_ROOT
    PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
if(OPENBLAS_INCLUDE_DIR AND OPENBLAS_LIBRARY)
    set(RLIRGEMM_HAS_OPENBLAS ON)
    add_library(OpenBLASLib INTERFACE)
    target_include_directories(OpenBLASLib INTERFACE "${OPENBLAS_INCLUDE_DIR}")
    target_link_libraries(OpenBLASLib INTERFACE "${OPENBLAS_LIBRARY}")
    # Existing GEMM CMake fragments consume these compatibility variables.
    set(OPENBLAS_INSTALL_DIR "${OPENBLAS_ROOT}")
    set(OPENBLAS_HOME "${OPENBLAS_INCLUDE_DIR}")
    set(OpenBlas_LIBRARY "${OPENBLAS_LIBRARY}")
    message(STATUS "OpenBLAS found: ${OPENBLAS_LIBRARY}")
else()
    set(RLIRGEMM_HAS_OPENBLAS OFF)
    message(STATUS "OpenBLAS not supplied; OpenBLAS and ml_gemm targets are disabled")
endif()

function(_rlirgemm_adapter target label)
    add_executable(${target} "${BASE_HOME}/gemm_main.cpp")
    target_include_directories(${target} PRIVATE "${BASE_HOME}" "${GEMM_HOME}"
        "${CMAKE_CURRENT_SOURCE_DIR}/baselines")
    target_compile_definitions(${target} PRIVATE _TRAIL_LABEL=${label}
        BENCH_OPT_O0=${BENCH_OPT_O0_VAL}
        CHECK_GEMM_RESULT_VAL=${CHECK_GEMM_RESULT_VAL})
endfunction()

set(_RLIRGEMM_BASELINE_TARGETS)
option(ENABLE_OPTIONAL_BASELINES "Create adapters for supplied optional prefixes" ON)
if(ENABLE_OPTIONAL_BASELINES AND RLIRGEMM_HAS_OPENBLAS)
  _rlirgemm_adapter(gemm_by_openblas openblas)
  target_include_directories(gemm_by_openblas PRIVATE
      "${OPENBLAS_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/openblas")
  target_link_libraries(gemm_by_openblas PRIVATE OpenBLASLib OpenMP::OpenMP_CXX)
  target_compile_definitions(gemm_by_openblas PRIVATE GEMM_BY_OPENBLAS)
  list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_openblas)
endif()

if(ENABLE_OPTIONAL_BASELINES)
  if(ARMPL_ROOT)
    find_path(ARMPL_INCLUDE_DIR NAMES cblas.h HINTS "${ARMPL_ROOT}" PATH_SUFFIXES include NO_DEFAULT_PATH)
    find_library(ARMPL_LIBRARY NAMES armpl_mp HINTS "${ARMPL_ROOT}" PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
    if(ARMPL_INCLUDE_DIR AND ARMPL_LIBRARY)
      _rlirgemm_adapter(gemm_by_armpl armpl)
      target_include_directories(gemm_by_armpl PRIVATE "${ARMPL_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/armpl")
      target_link_libraries(gemm_by_armpl PRIVATE "${ARMPL_LIBRARY}" OpenMP::OpenMP_CXX)
      target_compile_definitions(gemm_by_armpl PRIVATE GEMM_BY_ARMPL _ARMPL_USE_OMP)
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_armpl)
    else()
      message(WARNING "ARMPL_ROOT is set but cblas.h/armpl_mp is missing; target disabled")
    endif()
  endif()

  if(EIGEN_ROOT)
    find_path(EIGEN_INCLUDE_DIR NAMES Eigen/Core HINTS "${EIGEN_ROOT}" PATH_SUFFIXES include/eigen3 include NO_DEFAULT_PATH)
    if(EIGEN_INCLUDE_DIR)
      _rlirgemm_adapter(gemm_by_eigen eigen)
      target_include_directories(gemm_by_eigen PRIVATE "${EIGEN_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/eigen")
      target_link_libraries(gemm_by_eigen PRIVATE OpenMP::OpenMP_CXX)
      target_compile_definitions(gemm_by_eigen PRIVATE GEMM_BY_EIGEN)
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_eigen)
    else()
      message(WARNING "EIGEN_ROOT is set but Eigen/Core is missing; target disabled")
    endif()
  endif()

  if(BLIS_ROOT)
    find_path(BLIS_INCLUDE_DIR NAMES blis.h HINTS "${BLIS_ROOT}" PATH_SUFFIXES include/blis include NO_DEFAULT_PATH)
    find_library(BLIS_LIBRARY NAMES blis HINTS "${BLIS_ROOT}" PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
    if(BLIS_INCLUDE_DIR AND BLIS_LIBRARY)
      _rlirgemm_adapter(gemm_by_blis blis)
      _rlirgemm_adapter(gemm_by_blis_obj blis_obj)
      foreach(t IN ITEMS gemm_by_blis gemm_by_blis_obj)
        target_include_directories(${t} PRIVATE "${BLIS_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/blis")
        target_link_libraries(${t} PRIVATE "${BLIS_LIBRARY}" OpenMP::OpenMP_CXX)
      endforeach()
      target_compile_definitions(gemm_by_blis PRIVATE GEMM_BY_BLIS)
      target_compile_definitions(gemm_by_blis_obj PRIVATE _TRAIL_LABEL=blis_obj GEMM_BY_COMM_HEADER="by_blis_obj.h")
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_blis gemm_by_blis_obj)
    else()
      message(WARNING "BLIS_ROOT is set but blis.h/libblis is missing; targets disabled")
    endif()
  endif()

  if(BLASFEO_ROOT)
    find_path(BLASFEO_INCLUDE_DIR NAMES blasfeo.h HINTS "${BLASFEO_ROOT}" PATH_SUFFIXES blasfeo/include include NO_DEFAULT_PATH)
    find_library(BLASFEO_LIBRARY NAMES blasfeo HINTS "${BLASFEO_ROOT}" PATH_SUFFIXES blasfeo/lib lib lib64 NO_DEFAULT_PATH)
    if(BLASFEO_INCLUDE_DIR AND BLASFEO_LIBRARY)
      _rlirgemm_adapter(gemm_by_blasfeo blasfeo)
      target_include_directories(gemm_by_blasfeo PRIVATE "${BLASFEO_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/blasfeo")
      target_link_libraries(gemm_by_blasfeo PRIVATE "${BLASFEO_LIBRARY}" OpenMP::OpenMP_CXX)
      target_compile_definitions(gemm_by_blasfeo PRIVATE GEMM_BY_BLASFEO)
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_blasfeo)
    else()
      message(WARNING "BLASFEO_ROOT is set but blasfeo.h/libblasfeo is missing; targets disabled")
    endif()
  endif()

  if(LIBXSMM_ROOT)
    find_path(LIBXSMM_INCLUDE_DIR NAMES libxsmm.h HINTS "${LIBXSMM_ROOT}" PATH_SUFFIXES include NO_DEFAULT_PATH)
    find_library(LIBXSMM_LIBRARY NAMES xsmm libxsmm HINTS "${LIBXSMM_ROOT}" PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
    find_library(LIBXSMM_GENERATOR_LIBRARY NAMES xsmmgen libxsmmgen HINTS "${LIBXSMM_ROOT}" PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
    if(RLIRGEMM_HAS_OPENBLAS AND LIBXSMM_INCLUDE_DIR AND LIBXSMM_LIBRARY AND LIBXSMM_GENERATOR_LIBRARY)
      _rlirgemm_adapter(gemm_by_libxsmm libxsmm)
      target_include_directories(gemm_by_libxsmm PRIVATE "${LIBXSMM_INCLUDE_DIR}" "${OPENBLAS_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/libxsmm")
      target_link_libraries(gemm_by_libxsmm PRIVATE "${LIBXSMM_LIBRARY}" "${LIBXSMM_GENERATOR_LIBRARY}" "${OPENBLAS_LIBRARY}" OpenMP::OpenMP_CXX ${CMAKE_DL_LIBS})
      target_compile_definitions(gemm_by_libxsmm PRIVATE LIBXSMM_NOFORTRAN GEMM_BY_LIBXSMM EPPA_GEMM_PREFETCH_BL2)
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_libxsmm)
    else()
      message(WARNING "LIBXSMM_ROOT is set but headers/libraries are missing; target disabled")
    endif()
  endif()

  if(LIBSHALOM_ROOT)
    find_path(LIBSHALOM_INCLUDE_DIR NAMES LibShalom.h HINTS "${LIBSHALOM_ROOT}" PATH_SUFFIXES SMM/include include NO_DEFAULT_PATH)
    find_library(LIBSHALOM_LIBRARY NAMES smm libsmm HINTS "${LIBSHALOM_ROOT}" PATH_SUFFIXES SMM/lib lib lib64 NO_DEFAULT_PATH)
    if(LIBSHALOM_INCLUDE_DIR AND LIBSHALOM_LIBRARY)
      _rlirgemm_adapter(gemm_by_libshalom2 libshalom2)
      _rlirgemm_adapter(gemm_by_libshalom2_mp libshalom2_mp)
      foreach(t IN ITEMS gemm_by_libshalom2 gemm_by_libshalom2_mp)
        target_include_directories(${t} PRIVATE "${LIBSHALOM_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/libshalom2")
        target_link_libraries(${t} PRIVATE "${LIBSHALOM_LIBRARY}" OpenMP::OpenMP_CXX)
      endforeach()
      target_compile_definitions(gemm_by_libshalom2 PRIVATE GEMM_BY_LIBSHALOM2)
      target_compile_definitions(gemm_by_libshalom2_mp PRIVATE GEMM_BY_LIBSHALOM2_MP)
      # LibShalom may reorder FP32 reductions; allow the same small numerical
      # variation as its upstream benchmark while keeping the core checker at
      # its stricter default tolerance.
      foreach(t IN ITEMS gemm_by_libshalom2 gemm_by_libshalom2_mp)
        target_compile_definitions(${t} PRIVATE GEMM_RESULT_REL_TOL=1e-4f)
      endforeach()
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_libshalom2 gemm_by_libshalom2_mp)
    else()
      message(WARNING "LIBSHALOM_ROOT is set but LibShalom.h/libsmm is missing; targets disabled")
    endif()
  endif()

  if(CAKE_ROOT)
    find_path(CAKE_INCLUDE_DIR NAMES cake.h HINTS "${CAKE_ROOT}" PATH_SUFFIXES include NO_DEFAULT_PATH)
    find_library(CAKE_LIBRARY NAMES cake HINTS "${CAKE_ROOT}" PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
    find_library(CAKE_KERNEL_LIBRARY NAMES cake_kernels HINTS "${CAKE_ROOT}" PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
    if(CAKE_INCLUDE_DIR AND CAKE_LIBRARY AND CAKE_KERNEL_LIBRARY)
      _rlirgemm_adapter(gemm_by_cake cake)
      target_include_directories(gemm_by_cake PRIVATE "${CAKE_INCLUDE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/baselines/cake")
      target_link_libraries(gemm_by_cake PRIVATE "${CAKE_LIBRARY}" "${CAKE_KERNEL_LIBRARY}" OpenMP::OpenMP_CXX)
      target_compile_definitions(gemm_by_cake PRIVATE GEMM_BY_CAKE)
      list(APPEND _RLIRGEMM_BASELINE_TARGETS gemm_by_cake)
    else()
      message(WARNING "CAKE_ROOT is set but headers/libraries are missing; target disabled")
    endif()
  endif()

endif()

# Build every adapter whose prefix was found.
add_custom_target(gemm_baselines DEPENDS ${_RLIRGEMM_BASELINE_TARGETS})
